const ADD_TODO = "ADD_TODO";
const TODO_COMPLETED = "TODO_COMPLETED";
const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";

export {
  ADD_TODO,
  TODO_COMPLETED,
  FETCH_TODOS_REQUEST,
  FETCH_TODOS_SUCCESS,
  FETCH_TODOS_FAILURE,
};
